language: "zh"

pipeline:
- name: "JiebaTokenizer"
  dictionary_path: "data/jieba_userdict/jieba_userdict.txt"
- name: "RegexFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy